-- Non-redundant strain table, derived from heavy_metal_measurement.
-- The strain columns repeat on every colony row in the Parquet files. Checked 2026-10-07:
-- no strain_id has conflicting values for any of these columns, across all 5 metals.
-- Some rows carry NULL where other rows of the same strain have a value, so max()
-- (which ignores NULL) picks the one non-NULL value per strain.
-- strain_id is VARCHAR: 321 numeric IDs plus 13 'Control-N' labels that have no metadata.
-- species, ploidy and GWAS flags: taken from strain_curation (generated by scripts/curation/build_strain_curation.py,
-- loaded by 25_import_heavy_metal.py). species_screen keeps the original source value. The source text
-- 'Species Not Found' is a placeholder, not a NULL. Strains absent from strain_curation (controls) keep the source species.
-- ploidy_status: haploid / diploid_hybrid / diploid_other / unknown. gwas_panel: de-cloned haploid R. mucilaginosa panel (D-49).
-- Rows with NULL strain_id (10,921) belong to no strain and are excluded here.
CREATE OR REPLACE VIEW strain_info AS
SELECT
    m.strain_id,
    try_cast(m.strain_id AS INTEGER) IS NULL        AS is_control,
    max(m.SAMPLE_NAME)                              AS sample_name,
    max(m.STRAIN)                                   AS strain,
    coalesce(any_value(c.species), max(m.SPECIES))  AS species,
    max(m.SPECIES)                                  AS species_screen,
    coalesce(any_value(c.species_source), 'source data') AS species_source,
    any_value(c.clade_marker)                       AS clade_marker,
    coalesce(any_value(c.ploidy_status), 'unknown') AS ploidy_status,
    any_value(c.hybrid_subgroup)                    AS hybrid_subgroup,
    coalesce(any_value(c.in_callset) = 'True', false) AS in_callset,
    coalesce(any_value(c.gwas_panel) = 'True', false) AS gwas_panel,
    any_value(c.gwas_exclude_reason)                AS gwas_exclude_reason,
    any_value(c.curation_notes)                     AS curation_notes,
    max(m.MS2_SAMPLE_Cell)                          AS ms2_sample_cell,
    max(m.MS2_SAMPLE_Supernatant)                   AS ms2_sample_supernatant,
    max(m.Location)                                 AS location,
    list_sort(list(DISTINCT m.Metal))               AS metals_tested,
    count(*)                                      AS n_colony_observations
FROM heavy_metal_measurement m
LEFT JOIN strain_curation c ON c.strain_id = m.strain_id
WHERE m.strain_id IS NOT NULL
GROUP BY m.strain_id;

-- Per-strain, per-metal view that carries the source status, so Fe and Zn analyses can be filtered in SQL.
CREATE OR REPLACE VIEW strain_metal_status AS
SELECT s.strain_id, s.sample_name, s.species, s.ploidy_status, s.gwas_panel, u.metal, st.source_status
FROM strain_info s, UNNEST(s.metals_tested) AS u(metal)
JOIN metal_source_status st ON st.metal = u.metal;
