#!/usr/bin/env python3
"""Regenerate SCHEMA.md from the live database catalog.

Never hand-edit SCHEMA.md -- it's a snapshot of duckdb_tables()/
duckdb_columns()/duckdb_constraints(), regenerated on demand so it can't
drift from the real schema. Run after any migration. See
DATABASE_DESIGN.md §7.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.db import get_connection  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "SCHEMA.md"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default=None)
    ap.add_argument("--out", default=str(OUTPUT_PATH))
    args = ap.parse_args()

    con = get_connection(args.db)

    tables = con.execute(
        """
        SELECT table_name, table_type
        FROM information_schema.tables
        WHERE table_schema = 'main'
        ORDER BY table_type, table_name
        """
    ).fetchall()

    pk_cols = {}
    for row in con.execute(
        """
        SELECT table_name, constraint_column_names
        FROM duckdb_constraints()
        WHERE constraint_type = 'PRIMARY KEY'
        """
    ).fetchall():
        pk_cols[row[0]] = set(row[1])

    lines = [
        "# Database schema reference (generated)",
        "",
        "Generated by `scripts/db/40_data_dictionary.py` from the live DuckDB "
        "catalog -- do not hand-edit. See `DATABASE_DESIGN.md` for the design "
        "rationale behind this schema.",
        "",
    ]

    for table_name, table_type in tables:
        if table_type == "BASE TABLE":
            n_rows = con.execute(f'SELECT COUNT(*) FROM "{table_name}"').fetchone()[0]
            lines.append(f"## `{table_name}` ({n_rows:,} rows)")
        else:
            lines.append(f"## `{table_name}` (view)")
        lines.append("")
        lines.append("| Column | Type | Nullable | Primary key |")
        lines.append("| --- | --- | --- | --- |")
        cols = con.execute(
            """
            SELECT column_name, data_type, is_nullable
            FROM information_schema.columns
            WHERE table_name = ?
            ORDER BY ordinal_position
            """,
            [table_name],
        ).fetchall()
        pks = pk_cols.get(table_name, set())
        for col_name, data_type, is_nullable in cols:
            pk_mark = "yes" if col_name in pks else ""
            lines.append(f"| `{col_name}` | {data_type} | {is_nullable} | {pk_mark} |")
        lines.append("")

    Path(args.out).write_text("\n".join(lines))
    print(f"Wrote {args.out} ({len(tables)} tables/views)")


if __name__ == "__main__":
    main()
